config/routes.rb
Tsudaru::Application.routes.draw do
  resources :tweets, only: [:new, :create, :index]

  root :to => 'tweets#new'

  match "/delayed_job" => DelayedJobWeb, anchor: false
end

app/models/delayed_job.rb
# coding: utf-8

class DelayedJob < ActiveRecord::Base

end

app/models/tweet.rb
# coding: utf-8
class Tweet < ActiveRecord::Base
  attr_accessible :message, :hashtag, :speaker
  validate :tweet_message_less_than_140

  def tweet
    TwitterAPI.new.client.update(create_tweet_message)
    self.tweeted = true
    self.save
  rescue Twitter::Error => e
    if e.code == Twitter::Error::DuplicateStatus
      self.tweeted = true
      self.save
    else
     raise
    end
  end

  def tweet_message_less_than_140
    tweet_message = create_tweet_message
    if tweet_message.length > 140
      errors.add(:message, ": は140文字以内としてください")
    end
  end

  def create_tweet_message
    # Hashtagを表す#は意図的に付与しない
    "#{speaker}「#{message}」#{hashtag}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/delayed_jobs_controller.rb
class DelayedJobsController < ApplicationController
  def destroy
    dj = DelayedJob.find(params[:id])
    dj.destroy

    render template: "tweets/new"
  end
end

app/controllers/tweets_controller.rb
# coding: utf-8
class TweetsController < ApplicationController
   def new
      @tweet = Tweet.new
      @delayed_jobs = DelayedJob.order("created_at DESC").limit(5)
   end

   def create
     # 次のツイートの時にでも使う項目を設定
      @speaker = params[:tweet][:speaker]
      @hashtag = params[:tweet][:hashtag]

      @tweet = Tweet.new(params[:tweet])

      if @tweet.save
         @tweet.delay.tweet

         @tweet = Tweet.new
         @delayed_jobs = DelayedJob.order("created_at DESC").limit(5)

         render action: 'new'
      else
         @tweet.message = params[:tweet][:message]
         render action: 'new'
      end
   end

   def index
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tsudaru</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span10 offset2">
                <%= yield %>
            </div>
        </div>
    </div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
   <div id="error_explanation">
      <div class="alert alert-error">
         The form contains <%= pluralize(object.errors.count, "error") %>.
      </div>
      <ul>
         <% object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
         <% end %>
      </ul>
   </div>
<% end %>

app/views/tweets/_form.html.erb
現在の文字数は「<strong><span id="tweet_count" class="text-info"></span></strong>」です。
<div class="row-fluid">
    <%= form_for(@tweet, html: { class: "form-horizontal" }) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <div class="control-group">
            <div class="span2">
                <%= f.label :message, 'ツイート', class: "control-label" %>
            </div>
            <div class="controls span10">
                <%= f.text_area :message, rows: 3, class: "controls span10" %>
            </div>
        </div>
        <div class="control-group">
            <span class="control-label span1">　</span>
            <div class="controls form-inline">
                <%= f.label :hash_tag, "ハッシュタグ" %>
                <%= f.text_field :hashtag, value: @hashtag %>
                <%= f.label :speaker, "発表者" %>
                <%= f.text_field :speaker, value: @speaker %>
            </div>
        </div>
        <div class="form-actions">
            <div class="controls">
                <%= f.submit("送信", class: "btn btn-primary") %>
                <%= link_to "一覧に戻る", tweets_path, class: "btn" %>
            </div>
        </div>
    <% end %>
</div>

app/views/tweets/_recent_job_monitor.html.erb
<table class="table">
  <tr>
    <th>作成日時</th>
    <th>実行日時</th>
    <th>メッセージ</th>
    <th>試行回数</th>
    <th></th>
  </tr>

<% @delayed_jobs.each do |delayed_job| %>
  <tr>
    <td><%= delayed_job.created_at.in_time_zone("Tokyo") %></td>
    <td><%= delayed_job.run_at.in_time_zone("Tokyo") %></td>
    <td><%= truncate(YAML.load_dj(delayed_job.handler).message, length: 10) %></td>
    <td><%= delayed_job.attempts %></td>
    <td><%# link_to '削除', delayed_job_path(delayed_job), confirm: '削除しますか', method: :delete %></td>
  </tr>
<% end %>
</table>

app/views/tweets/new.html.erb
<%= render 'form' %>

<% if @delayed_jobs.size > 0 %>
  <%= render 'recent_job_monitor' %>
<% end %>
<%# link_to "ジョブモニタリング", delayed_job_path, target: "_blank" %>